apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-example-4
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: chaos-kafka
          image: chaos-kafka
          imagePullPolicy: IfNotPresent